/**/mask_to_3d:
  ros__parameters:
    base_frame_name: "base_footprint"
    mask_topic_name: "/masks_array"
    cloud_topic_name: "/point_cloud"
    info_topic_name: "/camera_info"
    
    # Point Cloud Processing
    cluster_tolerance: 0.04
    min_cluster_size: 50
    max_cluster_size: 20000
    noise_point_cloud_range: 0.01
    voxel_leaf_size: 0.01

    debug: false
    execute_default: true
